### ISSUE TITLE
Tutorial on Linear Algebra SUAD + ADIA 2023

### ISSUE THREAD

**Issue by sazio** [scaiworkshop/SUAD#1]
[Here a short](https://colab.research.google.com/gist/sazio/2305dfdfdc8b49a485b4a49638972388/linearalgebratutorial.ipynb) tutorial on linear algebra for the 2023 summer camp by SUAD and ADIA

**Comment by scaiworkshop** [comment]
It is added here: https://github.com/scaiworkshop/SUAD/tree/main/Day-1
